language: java
jdk: openjdk8
git:
    depth: false
script: ./build.sh
notifications:
    email: james.veitengruber@revature.net
    #enter your email address below
        - james.veitengruber@revature.net